### ISSUE TITLE
How do I "unshare" my note so that it will no longer be accessible to others?

### ISSUE THREAD

**Issue by jidloyola** [alangrainger/obsidian-share#16] opened 2023-10-02 14:14 UTC
This is fantastic plugin by the way. Now I finally have a reason to leave Craft for good. lol  But yeah, how do I unshare my note?

**Comment by alangrainger** [comment] 2023-10-02 14:19
Thanks for the feedback! Unshare/delete is currently in development, it will be available soon :)

Duplicate of #15

**Closed by alangrainger** 2023-10-02 14:19 UTC
