### ISSUE TITLE
[BUG] Massive gap between Banner header and note text

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#12] opened 2023-09-25 21:36 UTC
This has been happening a few times, not sure what triggers it: 

![gjgUsoVEBt](https://github.com/alangrainger/obsidian-share/assets/33608083/0c5f65f8-a786-427a-9f98-eade870223d6)

Here are the conditions that apply:

- The note has a banner
- **Show inline title** is off to prevent duplication of the title, since:
- The banner has a header (purple text)
- I've added a `---` divider to create spacing between the banner header and the start of the note text
    - Without this, then banner header overlaps the note text a bit (which is a separate issue) 

I can get the note back to normal the following way:
1. Remove the `---` line and Share note
2. Add the `---` line back and Share note

**Comment by FeralFlora** [comment] 2023-09-25 21:41
Here you can see the normal look of the note:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/bd41eaae-2748-47e4-b9ae-e037d76f65ab)

**Comment by alangrainger** [comment] 2023-09-26 06:13
Please upload a demo vault with a file where this is reproducible.

**Comment by FeralFlora** [comment] 2023-09-26 07:54
> Please upload a demo vault with a file where this is reproducible.

I believe it should be reproducible in the previously uploaded vault. Try creating an "invalid" numbered list in the note I shared, like:

```
1. The first list item
// Blank line
![[An image]]
// Blank line
2. The second list item
    1. Sub-list item
```

With the other conditions as is, including the `---` on the first line of the text. It seems to be happening consistently when I do the above.

**Comment by alangrainger** [comment] 2023-09-26 07:56
Works fine:

https://file.obsidianshare.com/a5/f6e445f44aa510b4eeb6a57874eb47f6.html#uFxW2VfPfqc239CpMAMGocULtMzAWcfKUvljNAU/CUw

Let me know when you have a demo vault.

**Comment by FeralFlora** [comment] 2023-09-26 07:58
@alangrainger I don't see a case of what I mentioned above? A list where there is a discontinuity between the numbers.

**Comment by alangrainger** [comment] 2023-09-26 08:01
I pasted your code directly as you sent it:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/5b932961-6be7-4dce-96c0-544d23be2ac3)

Is there something wrong with this?

**Comment by FeralFlora** [comment] 2023-09-26 08:03
> I pasted your code directly as you sent it:
> 
> ![image](https://user-images.githubusercontent.com/16197738/270581631-5b932961-6be7-4dce-96c0-544d23be2ac3.png)
> 
> Is there something wrong with this?

Yes, three things:

1. The `---` divider should be immediately after the yaml.
2. The blank line comments should be removed, so that there is an actual blank line.
3. The image should be an actual image

**Comment by alangrainger** [comment] 2023-09-26 08:04
Please post a demo file exactly as you want it.

**Comment by FeralFlora** [comment] 2023-09-26 08:06
Yes, here is the file as is now, which is running this issue intermittently: [Zotero Kanban Reading List guide.md](https://github.com/alangrainger/obsidian-share/files/12724812/Zotero.Kanban.Reading.List.guide.md)

To reproduce, I think you can try removing and adding the broken lists (uploading in between) I have down in "Quickadd setup" and the following sections so that I can insert images in between list items.

**Comment by alangrainger** [comment] 2023-09-26 08:13
Can't reproduce sorry. Closing this ticket as can't repro. If you can create a reproducible situation, please upload that demo vault / note.

https://file.obsidianshare.com/f7/5eb33df5ab5f40b202c9f7af958035a2.html#sFTgO+JVRIPnlXeoAPWGtquxWJDAfe4GlPoTgywVo58

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/588d296a-025d-4edd-94db-d360a0733a1e)

**Closed by alangrainger** 2023-09-26 08:13 UTC

**Comment by FeralFlora** [comment] 2023-09-26 08:20
This closing seems a bit rushed. I'm not saying that it happens every time. You have to be making changes, and I'm not exactly sure which ones, but it seems to be related to lists where I force the list number to increment, despite each list item being separate.

I currently have the note uploaded successfully here:
https://file.obsidianshare.com/70/e612da498b038c3e5e367043782e2b59.html#2xYueoh8c6BfX1CFcolBkeJx9D9KBEJ/jHGNRjCNx5Q

But it DOES happen intermittently, and I have to fix it by removing the first `---`, uploading (at this stage, the big space is gone), and then I add the `---` back, and re-upload.

**Comment by FeralFlora** [comment] 2023-09-26 08:23
> If that works it would let us know that it's a rendering delay in Obsidian. A delay like that would be device-dependent so hard to reproduce.

I will try that.

**Comment by alangrainger** [comment] 2023-09-26 09:54
> This closing seems a bit rushed

Don't feel rushed by that - it just means the issue is not yet reproducible. We can easily re-open the ticket again once there's an identifiable issue to fix.

Don't forget to try on different devices also. You can share from the phone and that might be another thing to test with.

**Comment by FeralFlora** [comment] 2023-09-26 11:02
> Don't feel rushed by that - it just means the issue is not yet reproducible.

Okay, kinda like this? https://medium.com/@dmkoelle/closed-cannot-reproduce-is-a-cop-out-use-stopped-investigating-instead-5d7809ffb534

**Comment by alangrainger** [comment] 2023-09-26 11:54
Once you figure out what specific combination of your note content + theme + CSS snippets + plugins + device + working process makes that issue occur, then I can figure out why Obsidian is exporting HTML like that and fix it 👍

**Comment by FeralFlora** [comment] 2023-09-26 12:00
> Once you figure out what specific combination of your note content + theme + CSS snippets + plugins + device + working process makes that issue occur, then I can figure out why Obsidian is exporting HTML like that and fix it 👍

Yeah, I will report back if I figure something out. It's difficult, though, since I don't upload on every change.

**Comment by alangrainger** [comment] 2023-09-26 12:34
I've increased the delay to wait after switching to Preview mode, but before extracting the HTML to upload.

Upgrade to 0.3.12 and see if that helps anything.

**Comment by FeralFlora** [comment] 2023-09-26 21:13
> I've increased the delay to wait after switching to Preview mode, but before extracting the HTML to upload.
> 
> Upgrade to 0.3.12 and see if that helps anything.

Nice! I'm keeping an eye out.
