### ISSUE TITLE
[BUG] Callout icons missing

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#11] opened 2023-09-25 20:48 UTC
I'm back, making sure there is an issue open...
On a serious note, it seems like some callout icons are not being display as expected, that is, they are not displayed at all.

The `tip` callout type is working:
Obsidian:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/44cdbe9d-acd8-448b-a4d3-d034a0b035ed)
Online:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/810d04b9-d527-459b-ae79-6b91444f7ffa)

But info and question are not:
Obsidian:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/e5f80e1d-e296-4471-b171-d8e358d204b0)
Online:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/4e10d8dd-1d89-46d0-b9ab-d09dbabb2782)

**Comment by FeralFlora** [comment] 2023-09-25 20:57
I am pretty sure that this was working previously, so I'm not sure what happened.

**Comment by alangrainger** [comment] 2023-09-25 21:01
Perhaps create a note which has all the features you need and force re-upload that one, to ensure all the features you need are compiled into your CSS.

**Comment by FeralFlora** [comment] 2023-09-25 21:15
> Perhaps create a note which has all the features you need and force re-upload that one, to ensure all the features you need are compiled into your CSS.

I tried force re-uploading, but the callout icons are still missing?

**Comment by alangrainger** [comment] 2023-09-25 21:20
Works fine for me in your demo vault 🤷‍♀️

https://file.obsidianshare.com/a5/f6e445f44aa510b4eeb6a57874eb47f6.html

**Comment by FeralFlora** [comment] 2023-09-25 21:28
> Works fine for me in your demo vault 🤷‍♀️
> 
> https://file.obsidianshare.com/a5/f6e445f44aa510b4eeb6a57874eb47f6.html

I was adding `+` making the callouts collapsible. Those are not in the test vault (at least not to the same extent). I think it has something to do with that. I got them to upload now after a few tries with force re-uploading. One callout was fixed by adding a title so it went from:
`> [!info]+` to `> [!info]+ Info`

and another, which already had a title, was fixed by removing the `+`.

**Comment by alangrainger** [comment] 2023-09-26 07:16
Ok, I can't reproduce it here, so I'll close this as can't repro. If you can find a way to make it happen, please upload a demo vault with the affected file.

Working fine with all `+ / -` options:

https://file.obsidianshare.com/a5/f6e445f44aa510b4eeb6a57874eb47f6.html#uFxW2VfPfqc239CpMAMGocULtMzAWcfKUvljNAU/CUw

**Closed by alangrainger** 2023-09-26 07:16 UTC
